<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <AssemblyName>DotNetCampus.AvaloniaInkCanvas</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="DotNetCampus.Numerics.Geometry" Version="$(DotNetCampusGeometryVersion)" />
    <PackageReference Include="DotNetCampus.Logger" Version="$(DotNetCampusLoggerVersion)" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="$(SourceLinkVersion)" Condition="'$(GITHUB_ACTIONS)' == 'true'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DotNetCampus.AvaloniaInkCanvas\**\*.cs" LinkBase="AvaloniaInkCanvas" />
    <Compile Include="..\DotNetCampus.InkCanvas.InkCore\**\*.cs" LinkBase="InkCore" />
    <Compile Include="..\DotNetCampus.InkCanvas.SkiaInk\**\*.cs" LinkBase="SkiaInk" />
  </ItemGroup>

</Project>
